import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import NavHead from '../components/NavHead'
import { Button } from '@mui/material';
import styles from '../styles/landingPage.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Quiz App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavHead />
     
      <main className={styles.main}>
       <div className={styles.landingImg}>
            <img src='/images/groupof3.png' />
       </div>
       <div className={styles.landingTxt}>
            <h2 className={styles.title2}>Welcome To The</h2>
            <h1 className={styles.title}>Quizapp</h1>
            <h6 className={styles.description}>
                 Answer Questions in limited time, Challenge Friends and climb the Leader Board
            </h6>
            <Button variant="contained" size="large" className={styles.signupButton} >
               Sign up
            </Button>
       </div>
      </main>
      {/* <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320" className={styles.svg}>
           <path fill="#1976D2" fill-opacity="1" d="M0,0L34.3,0C68.6,0,137,0,206,5.3C274.3,11,343,21,411,48C480,75,549,117,617,160C685.7,203,754,245,823,266.7C891.4,288,960,288,1029,293.3C1097.1,299,1166,309,1234,272C1302.9,235,1371,149,1406,106.7L1440,64L1440,320L1405.7,320C1371.4,320,1303,320,1234,320C1165.7,320,1097,320,1029,320C960,320,891,320,823,320C754.3,320,686,320,617,320C548.6,320,480,320,411,320C342.9,320,274,320,206,320C137.1,320,69,320,34,320L0,320Z"></path>
      </svg> */}
      {/* <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320" className={styles.svg} >
           <path fill="#1976D2" fillOpacity="1" d="M0,0L30,5.3C60,11,120,21,180,21.3C240,21,300,11,360,48C420,85,480,171,540,176C600,181,660,107,720,106.7C780,107,840,181,900,197.3C960,213,1020,171,1080,176C1140,181,1200,235,1260,256C1320,277,1380,267,1410,261.3L1440,256L1440,320L1410,320C1380,320,1320,320,1260,320C1200,320,1140,320,1080,320C1020,320,960,320,900,320C840,320,780,320,720,320C660,320,600,320,540,320C480,320,420,320,360,320C300,320,240,320,180,320C120,320,60,320,30,320L0,320Z"></path>
      </svg> */}
    </div>
  )
}

export default Home;
