import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Alert, AlertTitle, Button, FormControl, Input, InputLabel, Stack, TextField } from "@mui/material";
import { BsArrowLeftCircle } from "react-icons/bs";


import styles from '../styles/signUp.module.css'
import Link from 'next/link';


function signUp() {
  return (
    <div>
      <Head>
        <title>Sign Up Form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <div className={styles.top}>
          <Link href={"/"}>
            <BsArrowLeftCircle className={styles.top_icon} />
          </Link>
          <div>
            <p className={styles.topText}>
              <span>Already have an account?</span>
              <span>
                <Link href={"/sign-in"}>Sign in</Link>
              </span>
            </p>
          </div>
        </div>
        <div className={styles.bottom}>
          <div className={styles.simg}>
            <img src="/images/signup2.svg" />
          </div>
          <div className={styles.sform}>
            {/* <Stack sx={{ width: "100%" }} spacing={2}>
              <Alert severity="error">
                <AlertTitle>Error</AlertTitle>
                This is an error alert — <strong>check it out!</strong>
              </Alert>

              <Alert severity="success">
                <AlertTitle>Success</AlertTitle>
                This is a success alert — <strong>check it out!</strong>
              </Alert>
            </Stack> */}
            <form action="">
              <div className={styles.group}>
                <InputLabel htmlFor="email">Full Name</InputLabel>
                <input type="text" name="name" required />
              </div>
              <div className={styles.group}>
                <InputLabel htmlFor="email">Email address</InputLabel>
                <input type="email" name="" id="email" required />
              </div>
              <div className={styles.group}>
                <InputLabel htmlFor="email">Phone Number</InputLabel>
                <input type="phone" name="" id="phone" required />
              </div>
              <div className={styles.group}>
                <InputLabel htmlFor="email">Create Password</InputLabel>
                <input type="password" name="" id="" required />
              </div>
              <div className={styles.group}>
                <InputLabel htmlFor="email">Confirm Password</InputLabel>
                <input type="password" name="" id="" required />
              </div>
              <Button variant="contained" size="large" className={styles.signupButton}>
                Sign up
              </Button>
            </form>

            {/* <FormControl>
              <InputLabel htmlFor="my-input">Email address</InputLabel>
              <Input fullWidth id="my-input" aria-describedby="my-helper-text" className={styles.lnt} />
            </FormControl> */}
          </div>
        </div>
      </main>
    </div>
  );
}

export default signUp; 
